import Head from 'next/head';
import HomePage from './HomePage/HomePage';
import { useAppContext } from '@/Context/theme';

export default function Home() {

  // const myContext = useAppContext();
  // console.log(myContext.Theme)

  return (
    <>
      <Head>
        <title>Asack</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/image/dian.svg" />
      </Head>
      <main className='mainContainer'>
        <HomePage/>
      </main>
    </>
  )
}
